# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='alcoholemic_tax',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
