# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_auto_20161023_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='birthday',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='genre',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female')], default=None),
            preserve_default=False,
        ),
    ]
