# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_driver_alcoholemic_tax'),
        ('car', '0002_car_active_driver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caraccess',
            unique_together=set([('car', 'driver')]),
        ),
    ]
