# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20161024_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
