# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_driver_alcoholemic_tax'),
        ('car', '0004_auto_20161024_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.Driver')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='drivergroup',
            unique_together=set([('group', 'driver')]),
        ),
    ]
